spring:
  datasource:
    url: jdbc:mysql://localhost:3306/bloginfo?useSSL=false&serverTimezone=UTC&useLegacyDatetimeCode=false
    username: root
    password: Kukusiki39_7
jpa.hibernate.ddl-auto: create
jpa.show-sql: true











